### ISSUE TITLE
Add recently played

### ISSUE THREAD

**Issue by FelixGail** [BjoernPetersen/JMusicBot#45]
A method to retrieve recently played songs

**Comment by BjoernPetersen** [comment]
I actually already added an `isPlayed` field to `QueueEntry` in the unfinished new version of [JMusicBot-API](https://github.com/BjoernPetersen/JMusicBot-API).

Played songs are not even stored right now, which is why there is no method to retrieve them.
I'll implement all of this when I implement the new API.

**Comment by BjoernPetersen** [comment]
Closed by e5721875de5b7febb2548503aa462466a306be2a
